name = "riadhpackdz"
compatibility_date = "2026-04-13"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"